### ISSUE TITLE
Episodes date doesn't match real release date

### ISSUE THREAD

**Issue by Dgiulian** [BuildingXwithJS/BxJS-Website#24]
Episode 89 was released on 11/15/2019 but on the website it says from 11/22/2019. 
Episode 88 was released on 11/08/2019 but on the website, it says from 11/15/2019.

All the episodes weeks in the episodes list seems to be off by 1.

**Comment by yamalight** [comment]
@Dgiulian good catch! Seems like I've screwed up in my "date from week" calculations 😅

**Comment by Dgiulian** [comment]
There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors. 😉
