### ISSUE TITLE
News letter

### ISSUE THREAD

**Issue by FDiskas** [BuildingXwithJS/BxJS-Website#28]
I wish to subscribe to a newsletter - it can include ads if needed :)
It can be rss feed in worst case :)

**Comment by yamalight** [comment]
@FDiskas there is an RSS on the website [already](https://bxjs.dev/rss.xml).
I was thinking about newsletter, but have no idea how to organize this - if anyone has any suggestions - would be more than happy to do that 🤔

**Comment by FDiskas** [comment]
Try mailchimp.com for sending newsletters, they have API and also subscribe and unsubscribe implementation in their side

**Comment by FDiskas** [comment]
In your RSS feed should be more info. I hope that all content in feed would be available.
Currently I see this and it's useless:
![image](https://user-images.githubusercontent.com/468006/77427501-34d91d00-6ddf-11ea-8ad1-69dbdefa7183.png)

Good example of rss would be something like
![image](https://user-images.githubusercontent.com/468006/77427542-47ebed00-6ddf-11ea-8224-6f99ba0b17cc.png)

Ref: http://www.bernardinai.lt/rss/feeds/all

**Comment by FDiskas** [comment]
Oh, now I see that actually there is content included, but no rss readers could read it. Tried Opera browser internal RSS reader, Tried chrome plugin https://chrome.google.com/webstore/detail/rss-feed-reader/pnjaodmkngahhkoihejjehlcdlnohgmp
they are all shows just title. Probably you should check the syntax of your feed
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fbxjs.dev%2Frss.xml

Could it be a problem because of encoding? I see `&lt;li&gt;&lt;`  As I understand after `<![CDATA[` the content should not be encoded

**Comment by yamalight** [comment]
@FDiskas I'm using it in Feedly and it works fine, not sure why it wouldn't work in other readers. 🤔 
If you can figure it out - please do send a PR!
