### ISSUE TITLE
RSS feed for bxjs-weekly

### ISSUE THREAD

**Issue by Tiim** [BuildingXwithJS/BxJS-Website#3]
It would be nice to have an [RSS feed](https://en.wikipedia.org/wiki/RSS) for bxjs-weekly on the bxjs website.
This would allow people to subscribe to it either via their favourite RSS reader or for an example an IFTTT app that notifies them. 

* [nodejs rss library](https://www.npmjs.com/package/rss)

**Comment by yamalight** [comment]
Great idea, thanks for opening this! 👍

**Comment by yamalight** [comment]
RSS is now available here: https://bxjs.dev/rss.xml
