### ISSUE TITLE
Better caching headers in production

### ISSUE THREAD

**Issue by yamalight** [BuildingXwithJS/BxJS-Website#35]
Currently caching might prevent browser from fetching latest episode on home page, we should expire pages after 5 days.

**Comment by himankpathak** [comment]
Hey @yamalight,
I was going through the repo. I found out its a gatsby app.
To set cache-control property, you need to where the website is deployed ([Caching](https://www.gatsbyjs.com/docs/caching/))
As the headers are set on server when it sends files.
Do you have any ideas on how can I move forward with this?

**Comment by yamalight** [comment]
@himankpathak thanks for the interest!
Website is deployed using [official gastby docker image](https://github.com/gatsbyjs/gatsby-docker) via [custom Dockerfile](https://github.com/BuildingXwithJS/BxJS-Website/blob/develop/Dockerfile). 
Caching headers can be passed as env vars as far as I know

**Comment by himankpathak** [comment]
@yamalight, thanks for such a quick response. Really appreciated. I would look into the resources you provided.
Also, would you mind adding the "hacktoberfest" in repo topic, to make this an eligible repo for participating in hacktoberfest this year.
Thanks.

**Comment by yamalight** [comment]
@himankpathak I don't think adding topic is needed - just tagging eligible PRs should work

**Comment by himankpathak** [comment]
Thanks @yamalight. I just read the [update](https://hacktoberfest.digitalocean.com/hacktoberfest-update) regarding it.
