### ISSUE TITLE
Bug: Link is broken

### ISSUE THREAD

**Issue by yatki** [BuildingXwithJS/BxJS-Website#7]
I think some of the special characters in the article title has broken the link. See:
- Why '1', '7', '11'.map(parseInt) returns 1, NaN, 3 in Javascript 🖖 

https://bxjs.dev/weekly/19-24-Episode-67.md

**Comment by yamalight** [comment]
whoops, good catch! thanks for reporting :)

**Comment by yamalight** [comment]
seems that's a bug in markdown renderer website uses. links displays fine on github 🤔

**Comment by yamalight** [comment]
Should be good now.

**Comment by yatki** [comment]
Yup, works like a charm :D I noticed that old links are broken now, if you are thinking about SEO in the long run, would you consider having 301 redirects next time?

**Comment by yamalight** [comment]
Nah, I'm too lazy for that 😂
